version: '3'
services:
  devops:
    image: anjaneyulu02/devopsreponit:latest
    ports:
      - "95:80"
    deploy:
      replicas: 3

  azure:
    image: anjaneyulu02/azurereponit:latest
  ports:
    - "96:80"
  deploy:
    replicas: 3

  aws:
    image: anjaneyulu02/awsreponit:latest
  ports:
    - "97:80"
  deploy:
    replicas: 3

  datascience:
    image: anjaneyulu02/datascience:latest
  ports:
    - "98:80"
  deploy:
    replicas: 3
